# Generated by Django 5.1.2 on 2025-11-24 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Plan', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activities_json', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csat_app.user')),
            ],
        ),
    ]
