# Generated by Django 5.1.2 on 2025-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat_app', '0002_savedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='data_source',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
